buildSrc/src/main/kotlin/Dependencies.kt
buildSrc/src/main/kotlin/Versions.kt

https://trello.com/c/ZokvOkvr/45-add-in-auth0-support-on-the-web-side
- In order to use auth0 for authentication of a user, we need to add the dependency  into said project. This will be used along side Firebase, in order to setup user sign along with there actual data. 
- Add said dependency 
- Create a auth0 helper module for auth 0 functionality. 
- Firebase additional deps being added and functionality.

nick: Add in Auth0 Dependencies to project 

---

app/build.gradle.kts
app/src/main/java/com/nicholas/rutherford/track/my/shot/AppModule.kt
app/src/main/java/com/nicholas/rutherford/track/my/shot/MainActivity.kt
base-resources/src/main/java/com/nicholas/rutherford/track/my/shot/feature/splash/StringsIds.kt
base-resources/src/main/res/values/strings.xml
feature/create-account/build.gradle.kts
feature/create-account/src/main/java/com/nicholas/rutherford/track/my/shot/feature/create/account/CreateAccountNavigation.kt
feature/create-account/src/main/java/com/nicholas/rutherford/track/my/shot/feature/create/account/CreateAccountNavigationImpl.kt
feature/create-account/src/main/java/com/nicholas/rutherford/track/my/shot/feature/create/account/CreateAccountScreen.kt
feature/create-account/src/main/java/com/nicholas/rutherford/track/my/shot/feature/create/account/CreateAccountState.kt
feature/create-account/src/main/java/com/nicholas/rutherford/track/my/shot/feature/create/account/CreateAccountViewModel.kt
feature/create-account/src/test/java/com/nicholas/rutherford/track/my/shot/feature/create/account/CreateAccountViewModelTest.kt
feature/forgot-password/src/test/java/com/nicholas/rutherford/track/my/shot/feature/forgot/password/ForgotPasswordViewModelTest.kt
feature/login/src/main/java/com/nicholas/rutherford/track/my/shot/feature/login/LoginNavigationImpl.kt
feature/login/src/main/java/com/nicholas/rutherford/track/my/shot/feature/login/LoginScreen.kt
navigation/src/main/java/com/nicholas/rutherford/track/my/shot/navigation/NavigationActions.kt
navigation/src/main/java/com/nicholas/rutherford/track/my/shot/navigation/NavigationComponent.kt
navigation/src/main/java/com/nicholas/rutherford/track/my/shot/navigation/NavigationDestinations.kt
navigation/src/test/java/com/nicholas/rutherford/track/my/shot/navigation/NavigationActionsTest.kt
navigation/src/test/java/com/nicholas/rutherford/track/my/shot/navigation/NavigationDestinationsTest.kt

https://trello.com/c/4uec61X9/55-create-ui-around-create-account-view
- To integrate with firebase in the future, we need a pretty basic create account screen that takes in a username, email, and password. We currently don't have that screen, hence we need to create a new view. 
- Create said new UI 
- Introduce `:compose-components` module to introduce actual components in the app. 
- Intergate with realtime database -> firebase. 
- Prob some clean up with our UI screens we have been introducing. 
- N/A

nick: Create UI around Create Account View

---

compose-components/build.gradle.kts
compose-components/src/main/java/com/nicholas/rutherford/track/my/shot/compose/components/ContentWithTopBackAppBar.kt
feature/create-account/build.gradle.kts
feature/create-account/src/main/java/com/nicholas/rutherford/track/my/shot/feature/create/account/CreateAccountScreen.kt
feature/forgot-password/build.gradle.kts
feature/forgot-password/src/main/java/com/nicholas/rutherford/track/my/shot/feature/forgot/password/ForgotPasswordScreen.kt

https://trello.com/c/up2u71m9/57-turn-toolbar-and-content-view-to-a-stock-compose-component
- Since we now have a compose-component module, its the perfect time to introduce the `ContentWithTopBackAppBar` component. This component will get used for any screen, that as a back stack app bar that gets used. It is flexible to include the content when necessary 
- Create said component 
- Update `CreateAccountScreen` and `ForgotPasswordScreen` to use said component.  
- Turn the `TextField` with no padding that we are using for `CreateAccount` to include it as a component for retainability.
- N/A

nick: Turn toolbar and content view to a stock compose component

---

compose-components/src/main/java/com/nicholas/rutherford/track/my/shot/compose/components/TextFieldNoPadding.kt
feature/create-account/src/main/java/com/nicholas/rutherford/track/my/shot/feature/create/account/CreateAccountScreen.kt

https://trello.com/c/jqSdubb0/63-add-textfieldnopaddingcomponent
- In the create account ui workflow, we created a TextField that calculates to no padding start of the given text inside of the TextField. We are replicating this functionality every single time we want to use this, when we don’t really need to do that. Instead we can abstract this functionality out into a component; so that way it can be reused across given screens.
- Create a component called TextFieldNoPaddingComponent that is a simple component that adds no starting padding to the given textfield of the text inside of the `TextField`
- N/A 
- N/A

nick: Introduce TextFieldNoPadding component 

---

app-center/build.gradle.kts
app/build.gradle.kts
base-resources/build.gradle.kts
build-type/build.gradle.kts
buildSrc/src/main/kotlin/TaskOptions.kt
compose-components/build.gradle.kts
feature/create-account/build.gradle.kts
feature/forgot-password/build.gradle.kts
feature/home/build.gradle.kts
feature/login/build.gradle.kts
feature/splash/build.gradle.kts
helper/ui/build.gradle.kts
navigation/build.gradle.kts

https://trello.com/c/vYXQz1dx/58-add-automatic-ktlint-format-runs-as-part-of-our-build-process
- We need a way to execute `ktlintFormat` every single time that we run our project. This will make it so more things our caught as we are making changes, opposed to in the CI pipeline. 
- Add task job on each module level. 
- N/A

nick: Add automatic ktlint format runs as part of our build process for all of our modules 

---

app/build.gradle.kts
app/src/main/java/com/nicholas/rutherford/track/my/shot/AppModule.kt
app/src/test/java/com/nicholas/rutherford/track/my/shot/MyApplicationTest.kt
buildSrc/src/main/kotlin/Dependencies.kt
buildSrc/src/main/kotlin/Versions.kt
feature/splash/build.gradle.kts
feature/splash/src/main/java/com/nicholas/rutherford/track/my/shot/feature/splash/SplashViewModel.kt
feature/splash/src/test/java/com/nicholas/rutherford/track/my/shot/feature/splash/SplashViewModelTest.kt
firebase/read/build.gradle.kts
firebase/read/src/main/java/com/nicholas/rutherford/track/my/shot/firebase/read/ReadFirebaseUserInfo.kt
firebase/read/src/main/java/com/nicholas/rutherford/track/my/shot/firebase/read/ReadFirebaseUserInfoImpl.kt
firebase/read/src/test/java/com/nicholas/rutherford/track/my/shot/firebase/read/ReadFirebaseUserInfoImplTest.kt

https://trello.com/c/s4Qus3mc/66-update-splash-functionality-to-check-if-the-user-is-logged-in-before-navigating-to-login-or-home
- The splash screen functionality, does not currently check to see if a given user is logged in via firebase. If a account is logged in via Firebase, we should not take user to the login screen and instead; take user to the Home Screen.
- Add functionality to the splash screen, that checks to see if the user is logged in via firebase. If they are, take them to the Home Screen. If they re not; w e should then prompt them over to the login screen to login to a existing account; or create a account.
- N/A

nick: Update splash functionality to check if the user is logged in before navigating to login or home

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/nicholas/rutherford/track/my/shot/AppModule.kt
feature/create-account/build.gradle.kts
feature/create-account/src/main/java/com/nicholas/rutherford/track/my/shot/feature/create/account/CreateAccountViewModel.kt
feature/create-account/src/test/java/com/nicholas/rutherford/track/my/shot/feature/create/account/CreateAccountViewModelTest.kt
helper/network/build.gradle.kts
helper/network/src/main/java/com/nicholas/rutherford/track/my/shot/helper/network/Network.kt
helper/network/src/main/java/com/nicholas/rutherford/track/my/shot/helper/network/NetworkImpl.kt
helper/network/src/test/java/com/nicholas/rutherford/track/my/shot/helper/network/NetworkImplTest.kt
navigation/src/main/java/com/nicholas/rutherford/track/my/shot/navigation/NavigationComponent.kt

- N/A 
- We have a issue with the alert and progress mask only shows up one time via a screen 
- Issue were the `isDeviceConnectedToInternet` defined in `:helper:network` module sometimes doesn't actually return back a valid result. 
- Fix the alert and progress mask issue by actually setting the value of the alert and progress mask to null after the user closes both of them. This is so that way it can record a new event. 
- Rework the `isDeviceConnectedToInternet` by introducing sockets to attempt to connect to an actual network which is a more valid function call. 
- Add unit tests for `NetworkImpl` made myself a new task here for it: https://trello.com/c/18MPLEqC/88-add-unit-tests-to-networkimpl-class
- N/A

nick: Fix alert issue and rework the `NetworkImpl` functionality 

---

app/build.gradle.kts
app/src/main/java/com/nicholas/rutherford/track/my/shot/AppModule.kt
app/src/test/java/com/nicholas/rutherford/track/my/shot/MyApplicationTest.kt
base-resources/src/main/java/com/nicholas/rutherford/track/my/shot/feature/splash/StringsIds.kt
base-resources/src/main/res/values/strings.xml
buildSrc/src/main/kotlin/Dependencies.kt
buildSrc/src/main/kotlin/Versions.kt
data-test/account-info/src/main/java/com/nicholas/rutherford/track/my/shot/data/test/account/info/TestCreateAccountFirebaseAuthResponse.kt
data-test/account-info/src/main/java/com/nicholas/rutherford/track/my/shot/data/test/account/info/TestCreateAccountFirebaseRealtimeDatabaseResult.kt
data/account-info/src/main/java/com/nicholas/rutherford/track/my/shot/account/info/CreateAccountFirebaseAuthResponse.kt
data/account-info/src/main/java/com/nicholas/rutherford/track/my/shot/account/info/CreateAccountFirebaseRealtimeDatabaseResult.kt
firebase/create/build.gradle.kts
firebase/create/src/main/java/com/nicholas/rutherford/track/my/shot/firebase/create/CreateFirebaseUserInfo.kt
firebase/create/src/main/java/com/nicholas/rutherford/track/my/shot/firebase/create/CreateFirebaseUserInfoImpl.kt
firebase/create/src/test/java/com/nicholas/rutherford/track/my/shot/firebase/create/CreateFirebaseUserInfoImplTest.kt

https://trello.com/c/sZtuewUk/43-tie-in-firebase-creation-of-a-account-to-app-ability-to-create-profile-via-ui
- We currently don't have a realtime database method to ensure that when a user creates their account via email and password; that they actually attempt to also create a realtime database entry. This entry for now should contain the user username and email(password isn't saved due to security issues). 
- Create said method 
- Add tests 
- Since we have everything we need, finish the view model process to ensure we can complete the work flow. 
- N/A

nick: Add firebase realtime database method to create object for users info when creating a account

---

firebase/create/src/main/java/com/nicholas/rutherford/track/my/shot/firebase/create/CreateFirebaseUserInfoImpl.kt
firebase/create/src/test/java/com/nicholas/rutherford/track/my/shot/firebase/create/CreateFirebaseUserInfoImplTest.kt

- N/A 
- We want to change the naming from `userInfo` to `accountInfo` for where we save the users `email` and `username`. 
- Go ahead and make the naming change 
- Update tests
- N/A

nick: Change Realtime DB naming from `userInfo` to `accountInfo` 

---

app/src/main/java/com/nicholas/rutherford/track/my/shot/AppModule.kt
data-test/account-info/src/main/java/com/nicholas/rutherford/track/my/shot/data/test/account/info/realtime/TestAccountInfoRealTimeResponse.kt
data-test/account-info/src/main/java/com/nicholas/rutherford/track/my/shot/data/test/account/info/realtime/TestCreateAccountFirebaseRealtimeDatabaseResult.kt
data/account-info/src/main/java/com/nicholas/rutherford/track/my/shot/account/info/realtime/AccountInfoRealtimeResponse.kt
data/account-info/src/main/java/com/nicholas/rutherford/track/my/shot/account/info/realtime/CreateAccountFirebaseRealtimeDatabaseResult.kt
feature/create-account/src/main/java/com/nicholas/rutherford/track/my/shot/feature/create/account/authentication/AuthenticationViewModel.kt
feature/create-account/src/test/java/com/nicholas/rutherford/track/my/shot/feature/create/account/AuthenticationViewModelTest.kt
feature/splash/src/main/java/com/nicholas/rutherford/track/my/shot/feature/splash/SplashViewModel.kt
feature/splash/src/test/java/com/nicholas/rutherford/track/my/shot/feature/splash/SplashViewModelTest.kt
firebase/create/src/main/java/com/nicholas/rutherford/track/my/shot/firebase/create/CreateFirebaseUserInfoImpl.kt
firebase/create/src/test/java/com/nicholas/rutherford/track/my/shot/firebase/create/CreateFirebaseUserInfoImplTest.kt
firebase/read/build.gradle.kts
firebase/read/src/main/java/com/nicholas/rutherford/track/my/shot/firebase/read/ReadFirebaseUserInfo.kt
firebase/read/src/main/java/com/nicholas/rutherford/track/my/shot/firebase/read/ReadFirebaseUserInfoImpl.kt
firebase/read/src/test/java/com/nicholas/rutherford/track/my/shot/firebase/read/ReadFirebaseUserInfoImplTest.kt

https://trello.com/c/vJmFwKIu/81-introduce-a-getallusersaccountinfobyid-realtime-database-method
- We need a method to get account info in realtime database by a unique `email` identifier. This will look to see if the email is equal to the mapping reference and if so; will return back an account info response with require data. 
- We need a method to get the logged in `email` and returns tha data back via the flow. 
- Add in functions
- Add in tests 
- Clean up some existing methods names
- Add in a function that returns back a list of all account infos stored in the realtime firebase database. 
- N/A

nick: Introduce a getAccountInfoFlowByEmail realtime database method

---

base-resources/src/main/java/com/nicholas/rutherford/track/my/shot/feature/splash/StringsIds.kt
base-resources/src/main/res/values/strings.xml
feature/create-account/src/main/java/com/nicholas/rutherford/track/my/shot/feature/create/account/authentication/AuthenticationScreen.kt
feature/create-account/src/main/java/com/nicholas/rutherford/track/my/shot/feature/create/account/authentication/AuthenticationViewModel.kt
feature/create-account/src/test/java/com/nicholas/rutherford/track/my/shot/feature/create/account/AuthenticationViewModelTest.kt

https://trello.com/c/09KW6dzx/102-authentication-should-listen-to-whenever-a-user-go-aheads-and-confirms-there-account
- In the authentication flow; we don’t have a user indication to have the user check if the user has been authenticated yet. It is very possible; for a user to authenticate via their email or through another secondary phone.
- Add some CTA that calls the method to check if the account has been verified or not. If it has not been; show an alert to the user.
- N/A

nick: Authentication should have a spot on the UI where it checks to see if the account has been verified

---

base-resources/src/main/java/com/nicholas/rutherford/track/my/shot/feature/splash/StringsIds.kt
base-resources/src/main/res/values/strings.xml
compose-components/src/main/java/com/nicholas/rutherford/track/my/shot/compose/components/DialogWithTextField.kt
feature/create-account/src/main/java/com/nicholas/rutherford/track/my/shot/feature/create/account/createaccount/CreateAccountViewModel.kt
feature/create-account/src/test/java/com/nicholas/rutherford/track/my/shot/feature/create/account/CreateAccountViewModelTest.kt

https://trello.com/c/mXR681oZ/107-make-a-username-unique-when-creating-a-account
- When we are creating an account we require a custom password as well as custom email. We do this by using Regex matching so that way we don’t let custom emails or passwords through the creation process. We already ensure that a user cannot create an account with a already duplicate username we should ensure that a user; may never create an account with a non unique username.
- Apply the same logic for a custom username using regex so that way we have the same logic for password as well as email
- Update unit tests 
- N/A

nick: Make a username unique when creating a account

---

feature/login/src/androidTest/java/com/nicholas/rutherford/track/my/shot/feature/login/LoginScreenTest.kt
feature/login/src/main/java/com/nicholas/rutherford/track/my/shot/feature/login/LoginScreen.kt
feature/login/src/main/java/com/nicholas/rutherford/track/my/shot/feature/login/LoginTags.kt
feature/login/src/test/java/com/nicholas/rutherford/track/my/shot/feature/login/LoginTagsTest.kt
helper/compose-content-test-rule/src/main/java/com/nicholas/rutherford/track/myshot/compose/content/test/rule/ComposeContentTestRuleExtension.kt

- N/A 
- We want to have a new standard that every single time we create a Compose screen we had UI tests. This should test logic going on in the Compose screen. We currently don't have UI tests setup for `LoginScreen`.
- Setup tand update tests for `LoginScreen`. 
- Add more tests through the project. 
- N/A 
- N/A

nick: Update and add login tests to `LoginScreen`

---

data-test/firebase/src/main/java/com/nicholas/rutherford/track/my/shot/firebase/realtime/TestPlayerInfoRealtimeResponse.kt
data/firebase/src/main/java/com/nicholas/rutherford/track/my/shot/firebase/realtime/PlayerInfoRealtimeResponse.kt
firebase/create/src/main/java/com/nicholas/rutherford/track/my/shot/firebase/create/CreateFirebaseUserInfo.kt
firebase/create/src/main/java/com/nicholas/rutherford/track/my/shot/firebase/create/CreateFirebaseUserInfoImpl.kt
firebase/create/src/test/java/com/nicholas/rutherford/track/my/shot/firebase/create/CreateFirebaseUserInfoImplTest.kt
helper/constants/src/main/java/com/nicholas/rutherford/track/my/shot/helper/constants/Constants.kt

- https://trello.com/c/MW0nJ9DF/131-create-firebase-method-to-create-a-given-player
- We want to make an addition to our firebase realtime database to include the ability to create a player. The following will be data that will be uploaded up to the database that will include a table:
`data class PlayerInfoRealtimeResponse(val firstName: String = "",val lastName: String = "",val positionValue: Int = 0,val imageUrl: String = "")`
We will also need to ability to add more than player for a given user account, in order to support adding more than one player. The player itself should be sent up as a unique identify key, so that way we have the ability to retrieve a player by a key if necessary.
- Ability to create a player within realtime database with correct request type. This should also be …

nick: Create firebase method to create a given player

---

app/src/main/java/com/nicholas/rutherford/track/my/shot/AppModule.kt
data-test/firebase/src/main/java/com/nicholas/rutherford/track/my/shot/firebase/realtime/TestPlayerInfoRealtimeWithKeyResponse.kt
data/firebase/src/main/java/com/nicholas/rutherford/track/my/shot/firebase/realtime/PlayerInfoRealtimeWithKeyResponse.kt
feature/players/src/main/java/com/nicholas/rutherford/track/my/shot/feature/players/PlayersListViewModel.kt
firebase/core/build.gradle.kts
firebase/core/src/main/java/com/nicholas/rutherford/track/my/shot/firebase/core/delete/DeleteFirebaseUserInfo.kt
firebase/core/src/main/java/com/nicholas/rutherford/track/my/shot/firebase/core/delete/DeleteFirebaseUserInfoImpl.kt
firebase/core/src/main/java/com/nicholas/rutherford/track/my/shot/firebase/core/read/ReadFirebaseUserInfo.kt
firebase/core/src/main/java/com/nicholas/rutherford/track/my/shot/firebase/core/read/ReadFirebaseUserInfoImpl.kt
firebase/core/src/test/java/com/nicholas/rutherford/track/my/shot/firebase/core/delete/DeleteFirebaseUserInfoImplTest.kt
firebase/core/src/test/java/com/nicholas/rutherford/track/my/shot/firebase/core/read/ReadFirebaseUserInfoImplTest.kt

https://trello.com/c/4MaLDniP/143-firebase-method-to-delete-a-given-player
- We don't have a way in Firebase to delete a given player. We should have the ability to delete a player by a passed in player entire data class when necessary.
- Currently in the create fetch call to get given player info list; we are not getting back the actual firebase key reference to identify a player as a unique instance. We need to include that in the get response for later. 
- Introduce a function to delete a given player so long as the user passes in a `accountKey` which is unique to a given account, and a  `playerKey` which is unique to a player in a account. It will attempt to delete that player and then give back a boolean whether or not it's successful or not. 
- In the get call for getting players …

nick: Firebase method to delete a given player and update fetch player list to include the player firebase key

---

app/src/main/java/com/nicholas/rutherford/track/my/shot/AppModule.kt
firebase/core/src/main/java/com/nicholas/rutherford/track/my/shot/firebase/core/update/UpdateFirebaseUserInfo.kt
firebase/core/src/main/java/com/nicholas/rutherford/track/my/shot/firebase/core/update/UpdateFirebaseUserInfoImpl.kt
firebase/core/src/test/java/com/nicholas/rutherford/track/my/shot/firebase/core/update/UpdateFirebaseUserInfoImplTest.kt

https://trello.com/c/4MaLDniP/143-firebase-method-to-delete-a-given-player
- We don't have a way in Firebase to delete a given player. We should have the ability to delete a player by a passed in player entire data class when necessary.
- Add a way to delete a player via Firebase when necessary. This should take in a player type in order to delete it, if the player couldn't be deleted we should include additional info like the player didn't exist; or there was a network error.
- Room functions 
- N/A 
- N/A

nick: Firebase method to delete a given player

---

app/src/main/java/com/nicholas/rutherford/track/your/shot/AppModule.kt
app/src/main/java/com/nicholas/rutherford/track/your/shot/NavigationComponent.kt
feature/login/src/main/java/com/nicholas/rutherford/track/your/shot/feature/login/LoginViewModel.kt
feature/login/src/test/java/com/nicholas/rutherford/track/your/shot/feature/login/LoginViewModelTest.kt
helper/account/build.gradle.kts
helper/account/src/main/java/com/nicholas/rutherford/track/your/shot/helper/account/AccountAuthManagerImpl.kt
helper/account/src/test/java/com/nicholas/rutherford/track/your/shot/helper/account/AccountAuthManagerImplTest.kt

https://trello.com/b/UAh3A6Yj/project-track-my-shot
- When the user logs out of their given account, we want to clear the database completely. This is because when the user logins; we want new data and not save old account info data.
- Clear out the entire database when we logout.
= Players list empty state 
- Update players list UI 
- This is mostly the unit tests since the real code got merged in already which was weird that it did since I had protection rules on it. 
- n/a

Add a bulk login class that will clear out the database whenever the user logs out of their given account

---

data-test/firebase/src/main/java/com/nicholas/rutherford/track/your/shot/firebase/realtime/TestShotLoggedRealtimeResponse.kt
data-test/room/src/main/java/com/nicholas/rutherford/track/your/shot/data/test/room/TestShotLogged.kt
data/firebase/src/main/java/com/nicholas/rutherford/track/your/shot/firebase/realtime/ShotLoggedRealtimeResponse.kt
data/room/schemas/com.nicholas.rutherford.track.your.shot.data.room.database.AppDatabase/5.json
data/room/src/main/java/com/nicholas/rutherford/track/your/shot/data/room/database/AppDatabase.kt
data/room/src/main/java/com/nicholas/rutherford/track/your/shot/data/room/response/ShotLogged.kt
firebase/core/src/test/java/com/nicholas/rutherford/track/your/shot/firebase/core/create/CreateFirebaseLastUpdatedImplTest.kt
firebase/core/src/test/java/com/nicholas/rutherford/track/your/shot/firebase/core/read/ReadFirebaseUserInfoImplTest.kt
helper/account/src/main/java/com/nicholas/rutherford/track/your/shot/helper/account/AccountAuthManagerImpl.kt
helper/account/src/test/java/com/nicholas/rutherford/track/your/shot/helper/account/AccountAuthManagerImplTest.kt

- https://trello.com/c/OO2GbP1L/177-adding-ispending-field-to-the-shotlogged-data-class
- We want the ability that when a shot is logged to attach isPending field so that way we can know if a shot is pending or not. This will be used to trigger pending shot ideas when we go to create them.
- Introduce a new `isPending` field to ShotsLogged that way we can validate if the current shot were looking to law is pending or not.
- Use the new field, when we add a new shot to determine if the shot should be pending or not. 
- N/A 
- N/A

nick: Adding isPending field to the ShotLogged data class

---

app/src/main/java/com/nicholas/rutherford/track/your/shot/AppModule.kt
app/src/main/java/com/nicholas/rutherford/track/your/shot/MainActivityViewModel.kt
feature/login/src/main/java/com/nicholas/rutherford/track/your/shot/feature/login/LoginViewModel.kt
feature/login/src/test/java/com/nicholas/rutherford/track/your/shot/feature/login/LoginViewModelTest.kt
feature/players/shots/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/shots/SelectShotViewModel.kt
feature/players/shots/src/test/java/com/nicholas/rutherford/track/your/shot/feature/players/shots/SelectShotViewModelTest.kt
feature/players/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/playerlist/PlayersListViewModel.kt
feature/players/src/test/java/com/nicholas/rutherford/track/your/shot/players/playerlist/PlayersListViewModelTest.kt
feature/splash/src/main/java/com/nicholas/rutherford/track/your/shot/feature/splash/SplashViewModel.kt
feature/splash/src/test/java/com/nicholas/rutherford/track/your/shot/feature/splash/SplashViewModelTest.kt
helper/account/src/main/java/com/nicholas/rutherford/track/your/shot/helper/account/AccountManager.kt
helper/account/src/main/java/com/nicholas/rutherford/track/your/shot/helper/account/AccountManagerImpl.kt
helper/account/src/test/java/com/nicholas/rutherford/track/your/shot/helper/account/AccountManagerImplTest.kt

- https://trello.com/c/s5ayfuz0/179-create-a-function-that-deletes-ispending-shots-for-all-players
- We need a way to remove a player that has a shot pending associated with it. This should be done incase the user has logged a shot but wants to remove that shot or, if the user clears out the app while the shot is actively being logged; we shouldn’t be saving that pending shot. This function would then be called in two diffrent places:
1. When the user wants to not move forward with there shot logged
2. When the user clears out of the app while adding a player or logging shots that have not been saved.
- Add a function that fetches all players with a given account. Should then loop through all players, and check if there are shots logged. If there are shots logged, filter out all the shots …

nick: Create a function that deletes isPending shots for all players

---

app/src/main/java/com/nicholas/rutherford/track/your/shot/ScreenContents.kt
base-resources/src/main/java/com/nicholas/rutherford/track/your/shot/feature/splash/StringsIds.kt
base-resources/src/main/res/values/strings.xml
compose/components/src/main/java/com/nicholas/rutherford/track/your/shot/compose/components/BaseRow.kt
data-test/firebase/src/main/java/com/nicholas/rutherford/track/your/shot/firebase/realtime/TestShotLoggedRealtimeResponse.kt
data-test/room/src/main/java/com/nicholas/rutherford/track/your/shot/data/test/room/TestShotLogged.kt
data/firebase/src/main/java/com/nicholas/rutherford/track/your/shot/firebase/realtime/ShotLoggedRealtimeResponse.kt
data/room/schemas/com.nicholas.rutherford.track.your.shot.data.room.database.AppDatabase/7.json
data/room/src/main/java/com/nicholas/rutherford/track/your/shot/data/room/database/AppDatabase.kt
data/room/src/main/java/com/nicholas/rutherford/track/your/shot/data/room/response/ShotLogged.kt
feature/players/shots/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/shots/logshot/LogShotViewModel.kt
feature/players/shots/src/test/java/com/nicholas/rutherford/track/your/shot/feature/players/shots/logshot/LogShotViewModelTest.kt
feature/players/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/createeditplayer/CreateEditPlayerViewModel.kt
feature/players/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/createeditplayer/ext/ShotsContent.kt
helper/account/src/main/java/com/nicholas/rutherford/track/your/shot/helper/account/AccountManagerImpl.kt
helper/account/src/test/java/com/nicholas/rutherford/track/your/shot/helper/account/AccountManagerImplTest.kt

https://trello.com/c/uEdy6Fj6/170-ui-view-of-pending-shot-for-create-player-edit-player-workflow
- We currently are displaying pending shots from the UI view if the user was to go from the create or edit player workflow. We need to update UI view of how were displaying that 
- A pending shot doesn't come back with a pending shot name, which is something we want to display for a pending shot. 
- Update UI view 
- Make a new field in Room DB for a shotName that will come back from the pending shot. 
- Functionality that actually saves a pending shot to a current shot from edit and create player workflow. 
- Ability to go back to a pending shot and edit or view it before you make changes to it. 
- N/A 
- N/A

nick: Update UI view of a pending shot 

---

feature/players/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/createeditplayer/CreateEditPlayerViewModel.kt
feature/players/src/test/java/com/nicholas/rutherford/track/your/shot/players/createeditplayer/CreateEditPlayerViewModelTest.kt

https://trello.com/c/T1193MZQ/182-ability-to-save-a-pending-shot-to-a-active-shot-for-the-create-person-workflow
https://trello.com/c/N020pWqP/183-ability-to-save-a-pending-shot-to-a-active-shot-for-the-edit-person-workflow
- We currently didn't have the ability to actually save a player shot entry into Room and Realtime Firebase. It was always saving as an empty list and instead now that we have an instance of a pending shot, we need to convert that to proper `ShotLogged` data class value. 
- For both flows save a pending shot into the Room and Realtime Firebase, so that way that data can get saved when we make updates to the player. 
- Fix some weird issues where state property was updating to fast, causing some flashes between screens. 
- UI updates to shot info that we should be …

nick: Ability to save a pending player from the create / or edit player workflow 

---

feature/players/shots/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/shots/logshot/LogShotViewModel.kt
feature/players/shots/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/shots/logshot/pendingshot/CurrentPendingShot.kt
feature/players/shots/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/shots/logshot/pendingshot/CurrentPendingShotImpl.kt
feature/players/shots/src/test/java/com/nicholas/rutherford/track/your/shot/feature/players/shots/logshot/LogShotViewModelTest.kt
feature/players/shots/src/test/java/com/nicholas/rutherford/track/your/shot/feature/players/shots/logshot/pendingshot/CurrentPendingShotImplTest.kt

- N/A 
- Recently added ability to view pending and current shots, but there was never actual functionality to go back and update info of a pending shot until now. 
- Add the ability to delete a pending shot and then recreate it, after the info has been saved. In the future it may make sense just to update the shot rather then delete and recreate the show, but for now I am okay with doing it this way since its being updated from the direct state flow and updating from the state flow seems to be like pain vs updating a Dao call. 
- Ability to update an existing shot, which is gotta be alot more challenging seeing as the pending shot isn't waited to be changed upon saving or updating player info. 
- Add the ability for users to save more then just one shot on a empty state, they should save …

nick: Ability to edit info on a pending shot 

---

app/src/main/java/com/nicholas/rutherford/track/your/shot/NavigationComponent.kt

https://trello.com/c/8T0ahHvp/190-hide-navigation-to-stats-compare-player-and-stats-and-voice-commands-tabs
- We need to hide sheet actions since functionality is not set up for them, and they will not be released with said support for 1st release. 
- Comment them out, with a todo comment to uncomment them out once were ready to add functionality for them. 
- N/A 
- N/A 
- N/A

nick: Hide navigation to Stats, Compare Player and Stats, and Voice commands tabs

---

app/src/main/java/com/nicholas/rutherford/track/your/shot/AppModule.kt
app/src/main/java/com/nicholas/rutherford/track/your/shot/NavigationComponent.kt
base-resources/src/main/java/com/nicholas/rutherford/track/your/shot/feature/splash/StringsIds.kt
base-resources/src/main/res/values/strings.xml
data/room/src/main/java/com/nicholas/rutherford/track/your/shot/data/room/response/ShotLogged.kt
feature/players/shots/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/shots/logshot/LogShotViewModel.kt
feature/players/shots/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/shots/selectshot/SelectShotNavigation.kt
feature/players/shots/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/shots/selectshot/SelectShotNavigationImpl.kt
feature/players/shots/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/shots/selectshot/SelectShotViewModel.kt
feature/players/shots/src/test/java/com/nicholas/rutherford/track/your/shot/feature/players/shots/logshot/LogShotViewModelTest.kt
feature/players/shots/src/test/java/com/nicholas/rutherford/track/your/shot/feature/players/shots/selectshot/SelectShotViewModelTest.kt
feature/players/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/createeditplayer/CreateEditPlayerViewModel.kt
feature/players/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/createeditplayer/ext/ShotsContent.kt
feature/players/src/test/java/com/nicholas/rutherford/track/your/shot/players/createeditplayer/CreateEditPlayerViewModelTest.kt

- https://trello.com/c/BKNz2fyj/197-button-that-displays-if-you-have-no-pending-shots-and-at-least-one-saved-shot-to-allow-a-user-to-enter-another-shot
- Currently the user is tied to only really add one shot for one player. The user should be able to add as many shots as they want to the given player, so long as the user does not have a current pending shot they need to convert to an active shot. 
- The user has no way of telling if there shot info has been updated or not. 
- On the select shot screen there is an info button that is supposed to display more info for the user. Currently that button is not clickable and doesn't display that more info. 
- We currently allow the user to update a pending or active shot, despite the fact they have no changes. We should check to make sure the …

nick: CreateEditPlayer workflow updates 

---

app/src/main/java/com/nicholas/rutherford/track/your/shot/AppModule.kt
base-resources/src/main/java/com/nicholas/rutherford/track/your/shot/base/resources/StringsIds.kt
base-resources/src/main/res/values/strings.xml
compose/components/src/main/java/com/nicholas/rutherford/track/your/shot/compose/components/TextFieldNoPadding.kt
feature/create-account/build.gradle.kts
feature/create-account/src/main/java/com/nicholas/rutherford/track/your/shot/feature/create/account/createaccount/CreateAccountScreen.kt
feature/create-account/src/main/java/com/nicholas/rutherford/track/your/shot/feature/create/account/createaccount/CreateAccountViewModel.kt
feature/create-account/src/test/java/com/nicholas/rutherford/track/your/shot/feature/create/account/createaccount/CreateAccountViewModelTest.kt
feature/login/src/main/java/com/nicholas/rutherford/track/your/shot/feature/login/LoginViewModel.kt
feature/login/src/test/java/com/nicholas/rutherford/track/your/shot/feature/login/LoginViewModelTest.kt
helper/account/src/main/java/com/nicholas/rutherford/track/your/shot/helper/account/AccountManager.kt
helper/account/src/main/java/com/nicholas/rutherford/track/your/shot/helper/account/AccountManagerImpl.kt
helper/ui/src/main/java/com/nicholas/rutherford/track/your/shot/helper/ui/TextStyles.kt

- https://trello.com/c/gdpYLL73/220-bug-take-a-look-at-the-validatefieldswithoptionalalert-function-found-in-createaccountviewmodel
- https://trello.com/c/jjRR0VZS/219-have-a-disclosure-of-user-requirements-when-creating-account-for-username-email-password
- User on the create account workflow didn't really know what to enter for username, password, and email requirements. Different apps have different requirements, and we didn't really spell out in our cases what are the requirements for the app. 
- There was a bug where when we checked for errors in user entry on the create account workflow, that the error alerts didn't really make the most sense in the world. 
- Login and create account state wouldn't update correctly from both workflows. When a user logins in successfully then there …

nick: Helper text for create account, clear state on login updates, and alert for error on create account flow updates

---

app/src/main/java/com/nicholas/rutherford/track/your/shot/AppModule.kt
app/src/main/java/com/nicholas/rutherford/track/your/shot/NavigationComponent.kt
base-resources/src/main/java/com/nicholas/rutherford/track/your/shot/base/resources/StringsIds.kt
base-resources/src/main/res/values/strings.xml
feature/players/shots/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/shots/logshot/LogShotParams.kt
feature/players/shots/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/shots/logshot/LogShotScreen.kt
feature/players/shots/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/shots/logshot/LogShotState.kt
feature/players/shots/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/shots/logshot/LogShotViewModel.kt
feature/players/shots/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/shots/shotscreen/ShotScreen.kt
feature/players/shots/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/shots/shotscreen/ShotScreenNavigation.kt
feature/players/shots/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/shots/shotscreen/ShotScreenNavigationImpl.kt
feature/players/shots/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/shots/shotscreen/ShotScreenState.kt
feature/players/shots/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/shots/shotscreen/ShotScreenViewModel.kt
feature/players/shots/src/test/java/com/nicholas/rutherford/track/your/shot/feature/players/shots/logshot/LogShotViewModelTest.kt
feature/players/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/createeditplayer/CreateEditPlayerViewModel.kt
feature/players/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/playerlist/PlayersListViewModel.kt
feature/players/src/test/java/com/nicholas/rutherford/track/your/shot/players/createeditplayer/CreateEditPlayerViewModelTest.kt
feature/players/src/test/java/com/nicholas/rutherford/track/your/shot/players/playerlist/PlayersListViewModelTest.kt
firebase/core/src/main/java/com/nicholas/rutherford/track/your/shot/firebase/core/delete/DeleteFirebaseUserInfo.kt
firebase/core/src/main/java/com/nicholas/rutherford/track/your/shot/firebase/core/delete/DeleteFirebaseUserInfoImpl.kt
firebase/core/src/test/java/com/nicholas/rutherford/track/your/shot/firebase/core/delete/DeleteFirebaseUserInfoImplTest.kt
navigation/src/main/java/com/nicholas/rutherford/track/your/shot/navigation/NavigationDestinationsWithParams.kt

- https://trello.com/c/X80xCDBq/189-introduce-some-type-of-manager-class-to-help-with-createeditplayerviewmodel
- Currently the user did not have the ability to delete there given shots on there given account. We should be adding CRUD functionality for the user(Create, Read, Update, and Delete) a given shots logged by the user. 
- Add functionality that will search by a id to allow a user to delete there given shot and then update given UI. 
- N/A 
- N/A 
- N/A

nick: Ability to delete a shot from a given player

---

base-resources/src/main/java/com/nicholas/rutherford/track/your/shot/base/resources/StringsIds.kt
base-resources/src/main/res/values/strings.xml
feature/players/shots/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/shots/logshot/LogShotViewModel.kt
feature/players/shots/src/test/java/com/nicholas/rutherford/track/your/shot/feature/players/shots/logshot/LogShotViewModelTest.kt

https://trello.com/c/zgWLWB69/222-bug-user-should-not-be-able-to-move-forward-with-logging-a-shot-if-they-dont-enter-valid-shots-made-or-misses
- Currently in the app when the user enters shot made and misses, the number keypad pops up tot he user. They have the ability to enter decimal points which we don’t take. Currently if the user enters a decimal or invalid non whole number, the app crashes because it doesn’t know how to do the actual calculation.
- Noticed for an error alert for the log shot flow we were displaying an empty string for a title. It should display as Error. 
- Before we do any type of calculation read if the number is actually a valid number. If it is move forward with the intended process if not, then show some invalid state to the user.
- Fix the alert title 
- Add …

nick: Bug - User should not be able to move forward with logging a shot if they don't enter valid shots made or misses

---

buildSrc/src/main/kotlin/ConfigurationData.kt

- N/A 
- We need to up the versionName for the release to be `1.1`. The versionCode was already updated, but we should be updating the name for the new release. 
- Update the new version name to be from 1.0 to 1.1, for the new release. 
- N/A 
- N/A 
- N/A

nick: Up version name for new release to Google Play Console 

---

app/src/main/java/com/nicholas/rutherford/track/your/shot/AppModule.kt
app/src/main/java/com/nicholas/rutherford/track/your/shot/NavigationComponent.kt
base/vm/src/main/java/com/nicholas/rutherford/track/your/shot/base/vm/BaseViewModel.kt
feature/create-account/src/main/java/com/nicholas/rutherford/track/your/shot/feature/create/account/authentication/AuthenticationViewModel.kt
feature/create-account/src/test/java/com/nicholas/rutherford/track/your/shot/feature/create/account/authentication/AuthenticationViewModelTest.kt
feature/players/build.gradle.kts
feature/players/shots/build.gradle.kts
feature/players/shots/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/shots/selectshot/SelectShotViewModel.kt
feature/players/shots/src/test/java/com/nicholas/rutherford/track/your/shot/feature/players/shots/selectshot/SelectShotViewModelTest.kt
feature/players/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/playerlist/PlayersListViewModel.kt
feature/players/src/test/java/com/nicholas/rutherford/track/your/shot/players/playerlist/PlayersListViewModelTest.kt
helper/account/src/main/java/com/nicholas/rutherford/track/your/shot/helper/account/AccountManager.kt
helper/account/src/main/java/com/nicholas/rutherford/track/your/shot/helper/account/AccountManagerImpl.kt
helper/account/src/test/java/com/nicholas/rutherford/track/your/shot/helper/account/AccountManagerImplTest.kt

https://trello.com/c/7Nd5OpLS/232-removing-collecting-from-flows-from-the-accountmanager 
- There isn’t really a need to collect from Flows anymore at least what `AccountMnagaerImpl` gives me when logging in and logging out as far as shot / player data we get back from Firebase Realtime Database. Thats due to the fact that, we have implemented in the pass to call functionality when navigating to given screens vs when the app is loaded on the `NavigationComponent` side of things. So due to that when we login for example and observe Firebase calls to fill in the database, we could just fill in the database like where doing; and then from there call the Room database calls when navigating to the screen by using the `BaseViewModel` `onNavigatedTo` functionality. 
- Remove unnecessary flow …

nick: Removing collecting from Flows from the AccountManager

---

app/src/main/java/com/nicholas/rutherford/track/your/shot/NavigationComponent.kt
base-resources/src/main/java/com/nicholas/rutherford/track/your/shot/base/resources/StringsIds.kt
compose/components/src/main/java/com/nicholas/rutherford/track/your/shot/compose/components/BottomSheetWithOptions.kt
feature/players/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/createeditplayer/CreateEditPlayerParams.kt
feature/players/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/createeditplayer/CreateEditPlayerScreen.kt
feature/players/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/playerlist/PlayersListScreen.kt
feature/players/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/playerlist/PlayersListScreenParams.kt
feature/players/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/playerlist/PlayersListState.kt
feature/players/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/playerlist/PlayersListViewModel.kt
feature/players/src/test/java/com/nicholas/rutherford/track/your/shot/players/playerlist/PlayersListViewModelTest.kt

https://trello.com/c/1zcZ3A1q/234-update-player-list-selection-to-be-a-bottom-sheet-that-opens-when-clicking
- For the players list section we had the user click into an action image to the right of the row. When clicking on it they will be presented with the ability to delete / edit a player. This workflow was happening through a `DropdownMenu` which makes sense for this workflow but not this one. In the future the user would be able to do more then just edit / delete there player, so it makes sense to introduce this as a bottom sheet for more functional action items in the future. 
- The bottom sheet in question was also being used in the create / edit player workflow when selecting an image. Since its used more then once it makes sense to combine ui workflows into one components so we …

nick: Update player list selection to be a bottom sheet that opens when clicking
