rutherfn/track-your-shot

- code/.github/workflows/android_build.yml
https://trello.com/c/7cQXF7zy/6-attach-git-checks-for-repo
- We currently don't have any git checks forbid project. 
- Create said checks and validate that we can run them on pull request. 
- Testing around this.
> nick: Add git checks 

- .gitignore
- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/res/values/strings.xml
- buildSrc/src/main/kotlin/types/Build.kt
- buildSrc/src/main/kotlin/types/BuildTypes.kt
https://trello.com/c/LTSkZ8MP/23-create-multiple-releases-and-build-variants-for-given-project
- We should have multiple build variants / releases for said app when we upload to AppCenter. 
- .gitignore file was missing some proper documentation. 
- Create said multiple build variants / releases 
- Update code to include comment structure in gitignore file. 
- More build variants work
> nick: Create multiple releases / build variants and build variants for given project

- app/build.gradle.kts
- buildSrc/src/main/kotlin/types/BuildTypes.kt
- N/A 
- The stage build for this release should be `stage` not `staging` this was incorrect from my end. 
- Change release name from `stage` to `staging`
- N/A
> nick: Rename staging build to stage 

- buildSrc/src/main/java/AppCenter.kt
- N/A 
- In order to intergate AppCenter SDK for different application versions, we need to add said data class that will be brung in as dependencies when needed. 
- Define SDK data in the application. 
- Figure out a easy way to add secrets in some type ofclasu that can't be read and gets generated depending on which, App version we are pointing to.
> nick: Add AppCenter SDK Data 

- local.properties
- N/A 
- Local properties should never be included in the repo, and its actually on gitignore. 
- Just remove it and let cradle generate it!
> nick: ignore local properties 

- buildSrc/src/main/java/Room.kt
https://trello.com/c/8Wm8Ac6W/16-add-room-dependency
- We need to add Room dependency to given project for use. 
- Add said dependency
> nick: Add Room dependency 

- Miscellaneous/Tech Documents /Technical Design Document .md
- feature/splash/src/main/java/com/nicholas/rutherford/track/my/shot/feature/splash/SplashViewModel.kt
- N/A 
- One of the functions we introduced in `SplashViewModel` is not private when it should be 
- We need to update some existing documentation, since we are now introducing create and login to the app. 
- Make function private 
- Update some of the documentation 
- Update more documentation
> nick: Update function to private and update some documentation 

- app/src/main/java/com/nicholas/rutherford/track/my/shot/AppModule.kt
- base-resources/src/main/java/com/nicholas/rutherford/track/my/shot/feature/splash/Colors.kt
- base-resources/src/main/java/com/nicholas/rutherford/track/my/shot/feature/splash/DrawablesIds.kt
- base-resources/src/main/java/com/nicholas/rutherford/track/my/shot/feature/splash/StringsIds.kt
- base-resources/src/main/res/values/strings.xml
- feature/forgot-password/src/main/java/com/nicholas/rutherford/track/my/shot/feature/forgot/password/ForgotPasswordScreen.kt
- feature/login/build.gradle.kts
- feature/login/src/main/java/com/nicholas/rutherford/track/my/shot/feature/login/LoginScreen.kt
- feature/login/src/main/java/com/nicholas/rutherford/track/my/shot/feature/login/LoginState.kt
- feature/login/src/main/java/com/nicholas/rutherford/track/my/shot/feature/login/LoginViewModel.kt
- feature/login/src/test/java/com/nicholas/rutherford/track/my/shot/feature/login/LoginViewModelTest.kt
https://trello.com/c/VYMVA3Qh/53-clean-up-ui-around-login-screen
- We need to update the login UI to become more flexible with the layout that we have present. 
- Clean up UI 
- Add a new view state property for the circular image. 
- N/A
> nick: Clean up UI around Login screen

- buildSrc/src/main/kotlin/Versions.kt
- feature/splash/src/main/java/com/nicholas/rutherford/track/my/shot/feature/splash/SplashViewModel.kt
https://trello.com/c/ov18zELK/52-remove-auth0-from-project
- We are ditching Auth0 from said project, in to instead use Firebase Realtime database for user management; and storing data. 
- Remove Auth0 
- N/A
> nick: Remove Auth0 from project 

- feature/home/src/main/java/com/nicholas/rutherford/track/my/shot/feature/home/HomeScreen.kt
https://trello.com/c/DcLMLvEp/65-update-home-screen-to-just-include-a-button-for-logging-out-for-now
- We need a more obvious title for the button on the HomeScreen being of what it actually does. This is really just placeholder stuff, but as we start wiring in Firebase stuff to this; its gotta be important to correctly identify what were actually doing. 
- Just update text of button 
- N/A
> nick: Update Home Screen text button from Home to Log Out 

- app/build.gradle.kts
- app/src/main/java/com/nicholas/rutherford/track/my/shot/AppModule.kt
- app/src/test/java/com/nicholas/rutherford/track/my/shot/MyApplicationTest.kt
- base-resources/src/main/java/com/nicholas/rutherford/track/my/shot/feature/splash/StringsIds.kt
- base-resources/src/main/res/values/strings.xml
- feature/create-account/build.gradle.kts
- feature/create-account/src/main/java/com/nicholas/rutherford/track/my/shot/feature/create/account/CreateAccountViewModel.kt
- feature/create-account/src/test/java/com/nicholas/rutherford/track/my/shot/feature/create/account/CreateAccountViewModelTest.kt
- N/A 
- We should do a check before the user attempts to create an account if they are connected to internet. If they're not; we should display an alert. 
- Add check and alert and update unit tests. 
- More actual account creation stuff via firebase and UI.
> nick: Add a check before attempting to create account if user is connected to internet 

- app/src/main/java/com/nicholas/rutherford/track/my/shot/AppModule.kt
- app/src/test/java/com/nicholas/rutherford/track/my/shot/MyApplicationTest.kt
- feature/create-account/src/main/java/com/nicholas/rutherford/track/my/shot/feature/create/account/authentication/AuthenticationViewModel.kt
- feature/create-account/src/main/java/com/nicholas/rutherford/track/my/shot/feature/create/account/createaccount/CreateAccountViewModel.kt
- feature/create-account/src/test/java/com/nicholas/rutherford/track/my/shot/feature/create/account/AuthenticationViewModelTest.kt
- feature/create-account/src/test/java/com/nicholas/rutherford/track/my/shot/feature/create/account/CreateAccountViewModelTest.kt
- feature/home/build.gradle.kts
- feature/home/src/main/java/com/nicholas/rutherford/track/my/shot/feature/home/HomeNavigation.kt
- feature/home/src/main/java/com/nicholas/rutherford/track/my/shot/feature/home/HomeNavigationImpl.kt
- feature/home/src/main/java/com/nicholas/rutherford/track/my/shot/feature/home/HomeViewModel.kt
- feature/home/src/test/java/com/nicholas/rutherford/track/my/shot/feature/home/HomeViewModelTest.kt
- firebase/util/src/main/java/com/nicholas/rutherford/track/my/shot/firebase/util/authentication/AuthenticationFirebase.kt
- firebase/util/src/main/java/com/nicholas/rutherford/track/my/shot/firebase/util/authentication/AuthenticationFirebaseImpl.kt
- firebase/util/src/main/java/com/nicholas/rutherford/track/my/shot/firebase/util/existinguser/ExistingUserFirebase.kt
- firebase/util/src/main/java/com/nicholas/rutherford/track/my/shot/firebase/util/existinguser/ExistingUserFirebaseImpl.kt
- firebase/util/src/test/java/com/nicholas/rutherford/track/my/shot/firebase/util/authentication/AuthenticationFirebaseImplTest.kt
- firebase/util/src/test/java/com/nicholas/rutherford/track/my/shot/firebase/util/existinguser/ExistingUserFirebaseImplTest.kt
- navigation/src/main/java/com/nicholas/rutherford/track/my/shot/navigation/NavigationActions.kt
- navigation/src/test/java/com/nicholas/rutherford/track/my/shot/navigation/NavigationActionsTest.kt
https://trello.com/c/mxQMKyYk/100-ability-to-log-out-from-the-home-page
- We need functionality for the user to get logged out their account, when they are prompted to. As of right now we currently have no prompt so to test to make sure our log out functionality is working; we need to trigger it from the home button screen. 
- Add log out functionality by introducing a `ExistingUserFirebase` class that will be responsible for logging in and out users. 
- Clean up the home flow by add navigation. 
- Functionality for logging in an end user through the login screen. 
- N/A 
- N/A
> nick: Functionality to log end user out 

- app/src/main/java/com/nicholas/rutherford/track/my/shot/AppModule.kt
- app/src/test/java/com/nicholas/rutherford/track/my/shot/MyApplicationTest.kt
- base-resources/src/main/java/com/nicholas/rutherford/track/my/shot/feature/splash/StringsIds.kt
- base-resources/src/main/res/values/strings.xml
- feature/login/build.gradle.kts
- feature/login/src/main/java/com/nicholas/rutherford/track/my/shot/feature/login/LoginNavigation.kt
- feature/login/src/main/java/com/nicholas/rutherford/track/my/shot/feature/login/LoginNavigationImpl.kt
- feature/login/src/main/java/com/nicholas/rutherford/track/my/shot/feature/login/LoginScreen.kt
- feature/login/src/main/java/com/nicholas/rutherford/track/my/shot/feature/login/LoginState.kt
- feature/login/src/main/java/com/nicholas/rutherford/track/my/shot/feature/login/LoginViewModel.kt
- feature/login/src/test/java/com/nicholas/rutherford/track/my/shot/feature/login/LoginViewModelTest.kt
- firebase/create/src/test/java/com/nicholas/rutherford/track/my/shot/firebase/create/CreateFirebaseUserInfoImplTest.kt
- firebase/util/build.gradle.kts
- firebase/util/src/main/java/com/nicholas/rutherford/track/my/shot/firebase/util/existinguser/ExistingUserFirebase.kt
- firebase/util/src/main/java/com/nicholas/rutherford/track/my/shot/firebase/util/existinguser/ExistingUserFirebaseImpl.kt
- firebase/util/src/test/java/com/nicholas/rutherford/track/my/shot/firebase/util/existinguser/ExistingUserFirebaseImplTest.kt
- https://trello.com/c/CBPciz04/64-ability-to-login-into-a-account-via-firebase
- We never had actual functionality to login to an actual account via firebase through email / password. 
- Add existing functionality with unit tests. 
- Forgot password functionality.
> nick: Ability to login to a existing account with correct credentials 

- app/src/main/java/com/nicholas/rutherford/track/my/shot/AppModule.kt
- base-resources/src/main/java/com/nicholas/rutherford/track/my/shot/feature/splash/StringsIds.kt
- base-resources/src/main/res/values/strings.xml
- feature/forgot-password/build.gradle.kts
- feature/forgot-password/src/main/java/com/nicholas/rutherford/track/my/shot/feature/forgot/password/ForgotPasswordNavigation.kt
- feature/forgot-password/src/main/java/com/nicholas/rutherford/track/my/shot/feature/forgot/password/ForgotPasswordNavigationImpl.kt
- feature/forgot-password/src/main/java/com/nicholas/rutherford/track/my/shot/feature/forgot/password/ForgotPasswordScreen.kt
- feature/forgot-password/src/main/java/com/nicholas/rutherford/track/my/shot/feature/forgot/password/ForgotPasswordViewModel.kt
- feature/forgot-password/src/test/java/com/nicholas/rutherford/track/my/shot/feature/forgot/password/ForgotPasswordViewModelTest.kt
- feature/login/src/main/java/com/nicholas/rutherford/track/my/shot/feature/login/LoginViewModel.kt
- feature/login/src/test/java/com/nicholas/rutherford/track/my/shot/feature/login/LoginViewModelTest.kt
- firebase/util/src/main/java/com/nicholas/rutherford/track/my/shot/firebase/util/authentication/AuthenticationFirebase.kt
- firebase/util/src/main/java/com/nicholas/rutherford/track/my/shot/firebase/util/authentication/AuthenticationFirebaseImpl.kt
- firebase/util/src/test/java/com/nicholas/rutherford/track/my/shot/firebase/util/authentication/AuthenticationFirebaseImplTest.kt
- firebase/util/src/test/java/com/nicholas/rutherford/track/my/shot/firebase/util/existinguser/ExistingUserFirebaseImplTest.kt
https://trello.com/c/HmQHx1JC/60-ability-to-reset-a-current-account-password-in-the-app-with-the-forgotpassword-screen
- We want the ability to reset a given password on a email for the user via the login screen. We had the UI for it but never the functionality for it. 
- Add in said functionality
- Add in unit tests 
- More account validation additions.
> nick: Ability to reset a current account password in the app with the ForgotPassword screen

- buildSrc/src/main/kotlin/Dependencies.kt
- buildSrc/src/main/kotlin/Versions.kt
https://trello.com/c/91zJiKgB/101-add-in-timber-dependency
- We want to add in Timber dependency here: https://github.com/JakeWharton/timber  Timber allows us to add a logger to desired functions in order to see better in our console of errors or what's going on. This will help sort through potential areas of the code when logging it with Timber.
- Introduce said dependency.
- N/A 
- N/A
> nick: Add Timber depdendecy 

- firebase/read/build.gradle.kts
- firebase/read/src/main/java/com/nicholas/rutherford/track/my/shot/firebase/read/ReadFirebaseUserInfoImpl.kt
- N/A 
- We need to add timber logs for `ReadFirebaseUserInfo`
- Add in said timber logs
> nick: Add in timber logs for ReadFirebaseUserInfo

- firebase/read/src/main/java/com/nicholas/rutherford/track/my/shot/firebase/read/ReadFirebaseUserInfo.kt
- firebase/read/src/main/java/com/nicholas/rutherford/track/my/shot/firebase/read/ReadFirebaseUserInfoImpl.kt
- firebase/read/src/test/java/com/nicholas/rutherford/track/my/shot/firebase/read/ReadFirebaseUserInfoImplTest.kt
- helper/constants/src/main/java/com/nicholas/rutherford/track/my/shot/helper/constants/Constants.kt
https://trello.com/c/IqbBuezf/132-create-firebase-method-to-fetch-all-players
- We currently don't have a way to fetch a given player list from firebase realtime database. Because of that, we need to add a method that will allow us to fetch a lot of players. 
- Add firebase function that allows us to fetch a list of given players 
- Add unit tests. 
- N/A 
- N/A 
- N/A
> nick: Create firebase method to fetch all players

- app/build.gradle.kts
- app/src/androidTest/java/com/nicholas/rutherford/track/my/shot/fakes/FakeReadFirebaseUserInfo.kt
- app/src/androidTest/java/com/nicholas/rutherford/track/my/shot/tests/SplashUiTest.kt
- build.gradle
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/BuildIds.kt
- buildSrc/src/main/kotlin/ComposeData.kt
- buildSrc/src/main/kotlin/ConfigurationData.kt
- buildSrc/src/main/kotlin/Dependencies.kt
- buildSrc/src/main/kotlin/Versions.kt
- data/room/build.gradle.kts
- feature/login/build.gradle.kts
- feature/login/src/main/java/com/nicholas/rutherford/track/my/shot/feature/login/LoginScreen.kt
- gradle/wrapper/gradle-wrapper.properties
https://trello.com/c/4VTvYyKR/154-update-compose-library-dependencies
- We currently can't use the latest version of Compose in our project since alot of our dependencies are sort of out of date. This limits us to use everything that Compose really has to offer out of the gate.
- Implement latest Compose libraries by updating other dependencies that are needed.
- Show us using the latest Compose by introducing a preview to one of the screens,. 
- Move towards kip because that is needed to use latest version of Compose. 
- Create UI using latest version of Compose 
- N/A 
- N/A
> nick: Update Compose Library Dependencies

- app/src/main/java/com/nicholas/rutherford/track/your/shot/AppModule.kt
- app/src/main/java/com/nicholas/rutherford/track/your/shot/NavigationComponent.kt
- base-resources/src/main/java/com/nicholas/rutherford/track/your/shot/feature/splash/StringsIds.kt
- base-resources/src/main/res/values/strings.xml
- data-test/room/src/main/java/com/nicholas/rutherford/track/your/shot/data/test/room/TestPlayerEntity.kt
- data/room/src/androidTest/java/com/nicholas/rutherford/track/your/shot/data/room/ActiveUserEntityDaoTest.kt
- data/room/src/androidTest/java/com/nicholas/rutherford/track/your/shot/data/room/PlayerEntityDaoTest.kt
- data/room/src/androidTest/java/com/nicholas/rutherford/track/your/shot/data/room/PlayerRepositoryImplTest.kt
- data/room/src/main/java/com/nicholas/rutherford/track/your/shot/data/room/dao/PlayerDao.kt
- data/room/src/main/java/com/nicholas/rutherford/track/your/shot/data/room/entities/PlayerEntity.kt
- data/room/src/main/java/com/nicholas/rutherford/track/your/shot/data/room/repository/PlayerRepository.kt
- data/room/src/main/java/com/nicholas/rutherford/track/your/shot/data/room/repository/PlayerRepositoryImpl.kt
- data/room/src/main/java/com/nicholas/rutherford/track/your/shot/data/room/response/Player.kt
- feature/create-account/src/main/java/com/nicholas/rutherford/track/your/shot/feature/create/account/authentication/AuthenticationViewModel.kt
- feature/players/build.gradle.kts
- feature/players/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/PlayersListNavigation.kt
- feature/players/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/PlayersListNavigationImpl.kt
- feature/players/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/PlayersListScreen.kt
- feature/players/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/PlayersListScreenParams.kt
- feature/players/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/PlayersListViewModel.kt
- feature/players/src/test/java/com/nicholas/rutherford/track/your/shot/players/PlayersListNavigationImplTest.kt
- feature/players/src/test/java/com/nicholas/rutherford/track/your/shot/players/PlayersListViewModelTest.kt
- helper/account/src/main/java/com/nicholas/rutherford/track/your/shot/helper/account/AccountAuthManagerImpl.kt
- https://trello.com/c/BqbjoiI1/157-ability-to-delete-a-player
- : In the app, we currently don't have the ability to delete a given player from the user account. We should introduce that ability to delete a given player from the user account. The player should be delete not only on the local Room database but also, via Firebase Realtime Database.
- Ability to delete given player
- Added unit tests for given functionality 
- Introduce a create player screen 
- Introduce a view player screen 
- N/A 
- N/A
> nick: Ability to delete a player

- data/room/schemas/com.nicholas.rutherford.track.your.shot.data.room.database.AppDatabase/2.json
- data/room/schemas/com.nicholas.rutherford.track.your.shot.data.room.database.AppDatabase/3.json
- data/room/schemas/com.nicholas.rutherford.track.your.shot.data.room.database.AppDatabase/4.json
- data/room/src/main/java/com/nicholas/rutherford/track/your/shot/data/room/database/AppDatabase.kt
https://trello.com/c/tJH3oCNE/160-room-auto-migrations
- We want to introduce Room auto mirgations to the project so that way we don't have the rebuild the project every single time we make a change to said project. 
- Introduce Room auto migrations by introducing each entity on each version, bringing us to version 4. 
- N/A 
- N/A 
- N/A
> nick: Room Auto Migrations 

- app/src/androidTest/java/com/nicholas/rutherford/track/your/shot/tests/SplashUiTest.kt
- app/src/androidTest/java/com/nicholas/rutherford/track/your/shot/utility/TestUtil.kt
- base-resources/src/main/java/com/nicholas/rutherford/track/your/shot/feature/splash/StringsIds.kt
- base-resources/src/main/res/values/strings.xml
- compose/components/src/main/java/com/nicholas/rutherford/track/your/shot/compose/components/dialogs/ShotInputDialog.kt
https://trello.com/c/SxuLsB0O/196-update-log-shot-ui-dialog-when-adding-a-shot-made-vs-shot-missed
- `ShotInputDialog` had a issue where it would not delete the last number in the `TextField`, as well as the padding of the `title` of the actual dialog being off of the starting padding. 
- `ShotInputDialog` had a weird placeholder text that should be updated to just display the number of shot / shots the user has entered. 
- `TestUtil` despite the fact its not directly being used in automation test was running issues building its `NavigationComponent` because all the viewModels weren't passed to said component. 
- Fix the padding but by giving more starting padding to the title of the actual dialog contents. 
- Instead of relying on a regex to set the text, simply just check if the number …
> nick: Update log shot UI dialog when adding a shot made vs shot missed

- base-resources/src/main/res/values/strings.xml
- feature/players/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/createeditplayer/ext/ShotsContent.kt
- https://trello.com/c/2KncgF6i/199-make-pendingshots-and-current-shots-logged-on-player-list-screen-ui-in-sync
- Currently for the create / edit player view when you log a shot, the views that displays shots are out of sync. The UI should be the same across both.
- Update the UI for the pending shot view to match with the current log shot view.
- Clean up changes on this screen 
- N/A 
- N/A
> nick: Make PendingShots and current shots logged on player list screen UI in sync

- app/src/main/java/com/nicholas/rutherford/track/your/shot/AppModule.kt
- base-resources/src/main/java/com/nicholas/rutherford/track/your/shot/feature/splash/StringsIds.kt
- base-resources/src/main/res/values/strings.xml
- compose/components/src/main/java/com/nicholas/rutherford/track/your/shot/compose/components/TextFieldNoPadding.kt
- compose/components/src/main/java/com/nicholas/rutherford/track/your/shot/compose/components/dialogs/AlertDialog.kt
- compose/components/src/main/java/com/nicholas/rutherford/track/your/shot/compose/components/dialogs/CustomDatePickerDialog.kt
- compose/components/src/main/java/com/nicholas/rutherford/track/your/shot/compose/components/dialogs/ProgressDialog.kt
- feature/create-account/build.gradle.kts
- feature/create-account/src/main/java/com/nicholas/rutherford/track/your/shot/feature/create/account/authentication/AuthenticationNavigation.kt
- feature/create-account/src/main/java/com/nicholas/rutherford/track/your/shot/feature/create/account/authentication/AuthenticationNavigationImpl.kt
- feature/create-account/src/main/java/com/nicholas/rutherford/track/your/shot/feature/create/account/authentication/AuthenticationScreen.kt
- feature/create-account/src/main/java/com/nicholas/rutherford/track/your/shot/feature/create/account/authentication/AuthenticationViewModel.kt
- feature/create-account/src/main/java/com/nicholas/rutherford/track/your/shot/feature/create/account/createaccount/CreateAccountScreen.kt
- feature/create-account/src/main/java/com/nicholas/rutherford/track/your/shot/feature/create/account/createaccount/CreateAccountState.kt
- feature/create-account/src/main/java/com/nicholas/rutherford/track/your/shot/feature/create/account/createaccount/CreateAccountViewModel.kt
- feature/create-account/src/test/java/com/nicholas/rutherford/track/your/shot/feature/create/account/authentication/AuthenticationNavigationImplTest.kt
- feature/create-account/src/test/java/com/nicholas/rutherford/track/your/shot/feature/create/account/authentication/AuthenticationViewModelTest.kt
- feature/create-account/src/test/java/com/nicholas/rutherford/track/your/shot/feature/create/account/createaccount/CreateAccountViewModelTest.kt
- feature/login/src/main/java/com/nicholas/rutherford/track/your/shot/feature/login/LoginScreen.kt
- feature/players/src/main/java/com/nicholas/rutherford/track/your/shot/feature/players/createeditplayer/CreateEditPlayerViewModel.kt
- firebase/core/src/main/java/com/nicholas/rutherford/track/your/shot/firebase/core/create/CreateFirebaseUserInfoImpl.kt
- firebase/util/src/main/java/com/nicholas/rutherford/track/your/shot/firebase/util/authentication/AuthenticationFirebase.kt
- firebase/util/src/main/java/com/nicholas/rutherford/track/your/shot/firebase/util/authentication/AuthenticationFirebaseImpl.kt
- firebase/util/src/test/java/com/nicholas/rutherford/track/your/shot/firebase/util/authentication/AuthenticationFirebaseImplTest.kt
- helper/account/src/main/java/com/nicholas/rutherford/track/your/shot/helper/account/AccountManagerImpl.kt
- navigation/src/main/java/com/nicholas/rutherford/track/your/shot/navigation/NavigationActions.kt
https://trello.com/c/sFjKlVYH/215-do-not-clear-state-of-the-edited-or-current-player-until-after-the-user-has-navigated-to-the-player-list-screen-on-save-complete
https://trello.com/c/fv5xCBxn/212-update-the-alerts-ui
- There was a couple of UI bugs that needed to be addressed. 
- When we authenticate a user we should give the user the option to not move forward with the authentication process, if they want to start over with a new account. 
- Fix bugs 
- Allow the ability to have the user not authenticate moving forward with there account if they don't want to. 
- More settings functionality to finish up the app for first release. 
- N/A 
- N/A
> nick: Address small bugs found in app 

- Miscellaneous/Release/Release Schedule .md
https://trello.com/c/RtzTpKAm/34-create-a-external-release-schedule-of-the-app
- We should have a in detail schedule of versions timeline for the mobile app as well as; what's gotta go into every single release. This should follow a format to allow us to prepare and address certain features needed for certain releases; as well as keep myself on task with development related things.While we do have this currently it should be updated to include releases at least up to 2.0. We may want to come back in the future, and update this so will create an ongoing task for future releases.
- Update release schedule to account for future releases features to take into account. it should go from 1.0 to 2.0
- More release updates in the future. 
- N/A 
- N/A
> nick: Edit external release schedule of the app

- compose/components/src/main/java/com/nicholas/rutherford/track/your/shot/compose/components/dialogs/AlertDialog.kt
https://trello.com/c/NbKPIZM5
* Create rounded corners for alert dialogs
> Create rounded corners for alert dialogs

- app/src/main/java/com/nicholas/rutherford/track/your/shot/ScreenContents.kt
- feature/reports/src/main/java/com/nicholas/rutherford/track/your/shot/feature/reports/reportlist/ReportListNavigation.kt
- feature/reports/src/main/java/com/nicholas/rutherford/track/your/shot/feature/reports/reportlist/ReportListNavigationImpl.kt
- feature/reports/src/main/java/com/nicholas/rutherford/track/your/shot/feature/reports/reportlist/ReportListParams.kt
- feature/reports/src/main/java/com/nicholas/rutherford/track/your/shot/feature/reports/reportlist/ReportListScreen.kt
- feature/reports/src/main/java/com/nicholas/rutherford/track/your/shot/feature/reports/reportlist/ReportListViewModel.kt
- feature/reports/src/test/java/com/nicholas/rutherford/track/your/shot/feature/reports/reportlist/reportlist/ReportListNavigationImplTest.kt
https://trello.com/c/ES3X2opL/256-ability-to-view-downloaded-pdfs-in-the-app-for-reports
- In the app you don't have the ability to view reports in the app that you generated. We need to have said functionality.
- Add In the ability to view pdf saved reports of generated reports by players.
- One more before where ready to cut for a new release. 
- N/A 
- N/A
> nick: Ability to view downloaded pdfs in the app for reports

- app/src/main/java/com/nicholas/rutherford/track/your/shot/NavigationComponent.kt
- feature/shots/src/main/java/com/nicholas/rutherford/track/your/shot/feature/shots/ShotsListNavigation.kt
- feature/shots/src/main/java/com/nicholas/rutherford/track/your/shot/feature/shots/ShotsListNavigationImpl.kt
- feature/shots/src/main/java/com/nicholas/rutherford/track/your/shot/feature/shots/ShotsListScreen.kt
- feature/shots/src/main/java/com/nicholas/rutherford/track/your/shot/feature/shots/ShotsListScreenParams.kt
- feature/shots/src/main/java/com/nicholas/rutherford/track/your/shot/feature/shots/ShotsListViewModel.kt
- N/A 
- The shot list screen was waiting for the ability to filter your shots on that screen. I have decided for this release to not worry about filtering, and instead just add an education piece to this screen. 
- When clicking one education icon, it will show an alert stating what you can do on that screen. In the future,. we will be removing that functionality to allow the user to filter there shots. 
- Tiltering user shots. 
- N/A 
- N/A
> nick: Update shot list screen for education 

- buildSrc/src/main/kotlin/ConfigurationData.kt
- N/A 
- We just released 1.2 version of the app so due to that, we need to up the version name and change the version code. 
- Up version name and version code in the app. 
- N/A 
- N/A 
- N/A
> nick: Up the version name and code 
